In [4]:
import numpy as np
import pandas as pd

# Задание 1

In [5]:
def multiplication_order(A, B, C):
    # Получаем размеры матриц, учитывая условие, гарантирующее, что матрицы перемножаемы
    a, b = A.shape
    b, c = B.shape
    c, d = C.shape
    
    # результатом умножения матриц А и В будет матрица размера (а * с), каждый элемент которой получается суммой из b произведений 
    cost_a_b = b * (a * c)
    # считаем количество умножений для второго действия
    cost_ab_c = c * (a * d)
    # по аналогии просчитываем действия для второго варианта
    cost_b_c = c * (b * d)
    cost_a_bc = b * (a * d)

    # сравниваем два варианта
    if cost_a_b + cost_ab_c <= cost_b_c + cost_a_bc:
        return "(AxB)xC"
    else:
        return "Ax(BxC)"

# Проверим на тестовых данных    
A = np.array([[1,2]])
B = np.array([[2],[1]])
C = np.array([[5]])
    
multiplication_order(A, B, C)
#'(AxB)xC'

'(AxB)xC'

# Задание 2


In [30]:
#ваш код
def best_worst(X, Y):
    # Вычисляем коэффициенты корреляции между признаками X и ценами Y
    # Берем только последнюю строку (там корреляция с целевым вектором) и опускаем последний элемент, так как он будет равен 1
    corr = np.corrcoef(X.T, Y.T)[-1][:-1]

    # Находим индексы максимального и минимального значений корреляций по модулю
    max_corr_idx = np.argmax(np.abs(corr))
    min_corr_idx = np.argmin(np.abs(corr))

    return max_corr_idx, min_corr_idx

# Проверим на тестовых данных
data = np.array([
    [3,51,3,0,1,0,2200],
    [1,30,1,0,1,0,1600],
    [2,45,2,0,1,0,1900],
    [3,55,1,0,1,0,2000],
    [1,45,3,1,0,0,4500],
    [3,100,3,1,0,0,7000],
    [2,71,2,1,0,0,5000],
    [1,31,2,0,0,1,1700],
    [3,53,5,0,0,1,2100],
    [1,33,3,0,0,1,1500],
    [2,43,5,0,0,1,2000],
])
df = pd.DataFrame(data=data, columns=['Комнаты', 'Площадь', 'Этаж', 'Центр?', 'Спальный1?', 'Спальный 2?', 'Цена'])

X = df[['Комнаты', 'Площадь', 'Этаж', 'Центр?', 'Спальный1?', 'Спальный 2?']]
y = df[['Цена']]

best_worst(X,y)
#(3, 2)


(3, 2)

# Задание 3


In [31]:
#ваш код
def corr_rank(X):
    #строим матрицу корреляций
    corr = np.corrcoef(X)
    # возвращаем ранг матрицы корреляций
    return np.linalg.matrix_rank(corr)

corr_rank(X)
#5

5

# Задание 4

In [33]:
#ваш код
def inverse_matrix(A):
    if np.abs(np.linalg.det(A)) < 0.001:
        return None
    return np.linalg.inv(A)

A = np.array([[1, 2], [2, 1]])

print(inverse_matrix(A))
#array([[-0.33333333, 0.66666667],[ 0.66666667, -0.33333333]])

[[-0.33333333  0.66666667]
 [ 0.66666667 -0.33333333]]


# Задание 5

In [37]:
#ваш код
def fit_model(X, y):
    return (inverse_matrix(X.T@X)@X.T@y).to_numpy()

print(fit_model(X, y))

[[-574.12295766]
 [  65.33255763]
 [ 141.80223878]
 [1566.16246224]
 [  12.32450391]
 [-315.34552489]]
